### ISSUE TITLE
Очень лишнее действие

### ISSUE THREAD

**Issue by evilunyuu** [NeshtaNesht/cpp_zachet#2]
https://github.com/NeshtaNesht/cpp_zachet/blob/8ec3427c3fda0bf6ca6c6fcae44205405b5cbc5e/index.cpp#L46

Вот тут seed-ить генератор не имеет смысла, если он инициализирован уже с помощью random_device. Более того, использование random_device даёт куда лучшую энтропию, чем использование seed от времени.

**Comment by NeshtaNesht** [comment]
Просто у меня при повторном запуске приложения одни и те же числа показывались. Вот я и решил seed юзать, чтобы генерились разные числа.
