### ISSUE TITLE
Предсказуемая последовательность

### ISSUE THREAD

**Issue by evilunyuu** [NeshtaNesht/cpp_zachet#3]
https://github.com/NeshtaNesht/cpp_zachet/blob/bdb2e2c73937c779c114cc3addf40ce994db5338/index.cpp#L49-L50
Вот от такого генератора последовательность будет генерироваться одна и та же при каждом запуске программы. Зачем вообще второй генератор, если есть нормально инициализированный первый?

**Comment by NeshtaNesht** [comment]
Когда писал, то у меня генерировались одинаковые числа. Решил написать новый генератор для второго вектора. Щас проверил - оказалось зря.

**Comment by NeshtaNesht** [comment]
Нашел ошибку, почему каждый раз генерились одинаковые примеры при запуске. Исправил.
