### ISSUE TITLE
А зачем каждый раз заново создаётся генератор случайных чисел? 

### ISSUE THREAD

**Issue by evilunyuu** [NeshtaNesht/cpp_zachet#4]
https://github.com/NeshtaNesht/cpp_zachet/blob/b704b3d9cd6194154d5ead5d424915b088a9323a/index.cpp#L30-L38

Может, правильнее будет его сделать глобальным?

**Comment by NeshtaNesht** [comment]
Ну это я уже называется наujdyjкодил.

**Comment by evilunyuu** [comment]
https://github.com/NeshtaNesht/cpp_zachet/blob/fd097c7de048c1037c2ca9a27894dced1cb1ceac/index.cpp#L32-L37

И снова он тут создаётся каждый раз при входе в функцию... Если уж делать это классом, то наверное имеет смысл сделать генератор полем и создавать его один раз в конструкторе, а эти методы пусть его уже потом доят.
