### ISSUE TITLE
Опять практически  time() ...

### ISSUE THREAD

**Issue by evilunyuu** [NeshtaNesht/cpp_zachet#5]
https://github.com/NeshtaNesht/cpp_zachet/blob/b704b3d9cd6194154d5ead5d424915b088a9323a/index.cpp#L41-L45

Зачем-то опять создаётся новый ГПСЧ, так ещё и инициализируется временем, при живом (пусть и закомментированном) random_device.
Наверное, имеет смысл сделать один общий глобальный ГПСЧ на обе функции (эту и предыдущую)?

**Comment by NeshtaNesht** [comment]
вынес в класс. Теперь при инициализации с random_device числа формируются одинаковые...

**Comment by evilunyuu** [comment]
https://github.com/NeshtaNesht/cpp_zachet/issues/4#issuecomment-631528459

**Comment by NeshtaNesht** [comment]
Зачекинил. И походу что-то я опять неверно делаю. Вынес в глобал. Но каждый раз при запуске числа одни и те же.

**Comment by evilunyuu** [comment]
![Снимок экрана_2020-05-20_20-24-44](https://user-images.githubusercontent.com/12897761/82464897-0f634980-9ad8-11ea-9ea3-e3ccb6bc5d36.png)
Странно, у меня всё нормально.

**Comment by NeshtaNesht** [comment]
Windows же у меня))

**Comment by evilunyuu** [comment]
В общем, принято.
